const Models = require('./models/db')
const express = require('express')
const app = express()
app.get('/user/get', (req, res) => {
  console.log(req)
  console.log(res)
  // console.log(Models)
  res.send('get訪問成功')
})
app.post('/user/post', (req, res) => {
  console.log(req)
  console.log(res)
  res.send('post訪問成功')
})
app.post('/user/login', (req, res) => {
  console.log(req)
  console.log(res)
  res.send('login訪問成功')
})
app.listen(9500, () => console.log('************* [伺服器啟動成功] *************'))
